version: '3.8'

services:
  db:
    image: postgres:13
    container_name: spring-petclinic-db
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: spring-petclinic:multistage
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data: